# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest


# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

stages:
  - build
  - test
  - deploy



install dependencies:
  stage: build
  script: 
           - npm install

Test:
  stage: test
  script: 
          - npm test

Publish:
  stage: deploy
  script: 
          - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
          - npm publish

